### ISSUE TITLE
Missing Cancel Button on Password Reset Dialog Box

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-angular-authn-password#2]
There is no Cancel Button in the dialog box that is presented to the user when the click "Forgot your password" on the Sign in screen.

**Comment by mattcollier** [comment]
Although there is no cancel button, it is possible to close the modal by clicking the X in the upper right hand corner. 

Marking this as an enhancement.

**Comment by RobTrainer** [comment]
I am ok with it being an enhancement but I think the UI needs to be gone over for consistency and basic best practices for UI design.

**Comment by mattcollier** [comment]
We agreed in our meeting today to implement this.
