### ISSUE TITLE
Convert the password confirmation directive to a component.

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-angular-authn-password#4]
And use `ng-change` instead of `$watchGroup` if possible.

https://github.com/digitalbazaar/bedrock-authn-password/issues/8

**Comment by mattcollier** [comment]
Password reset form now uses `sameAs` directive from `bedrock-angular-form` landed: https://github.com/digitalbazaar/bedrock-angular-authn-password/commit/306f4b338bd19afff06e8d128f3ea6b1e4495040
